r4ss/r4ss

- R/SSplotComparisons.R
this is also a test whether I understand how to do a pull request after having forked.
> caught spelling error

- R/mcmc.out.R
Changes to mcmc.out from @allanhicks look good so pulling into main branch to make revised function easier to access.
> Hake2015mods allan

- R/SS_output.R
@taylori you may want to check my additions before merging. I am a bit behind on "proper" r4ss protocol. I tested it under a few scenarios, but I only have a limited number of ss3 versions on my computer.
> Add bias_adjustment_ramp to SS_output

- R/SS_RunJitter.R
- man/SS_RunJitter.Rd
Updated SS_RunJitter.R to accept a vector of iterations, so you can restart a jitter at an arbitrary number rather than having to run from 1:Njitter only. Also added a return of the likelihood values for each iteration if converged. This is under the assumption that SS pulls the random seed from a clock or something, thus if you run 1:50 on one machine and 51:100 on another machine they will not be using the same par values. Something that might need to be checked.
> Jitteriter

- R/SSunavailableSpawningOutput.R
New function to calculate and plot spawning output unavailable to the
fisheries
> SSunavailableSpawningOutput

- R/SSunavailableSpawningOutput.R
Thanks @allanhicks for finding this bug, noting the issue as #145, and fixing it.
> Unavailable ss bfix for seas

- R/SS_writedat.R
- R/SSplotComps.R
- man/SSplotComps.Rd
Sorts out issue #152.
This branch also includes updated SS_writedat because I accidentally committed it to the branch instead of the trunk.
> Comps by mkt branch revises aggregated comps

- R/SSplotCatch.R
- man/SSplotCatch.Rd
Revised catch plot for non-contiguous numbering of fleets with catch seems to be working OK (as discussed under issue #133), so merging branch.
> fix to SSplotCatch noted in issue #133

- R/SS_readctl_3.24.R
https://github.com/r4ss/r4ss/issues/178
> Dealing with selectivity blocks

- R/SSplotSpawnrecruit.R
- man/SS_readforecast.Rd
- man/SSplotSpawnrecruit.Rd
Fixes two R CMD check warnings
> Add argument 'show_env' to help page & roxygenize

- .travis.yml
https://stackoverflow.com/a/47781757
Might also need to disable the cache to re-cache packages if it doesn't work at first.
> Try and fix Travis error

- DESCRIPTION
- NEWS.md
- R/NegLogInt_Fn.R
- R/SS_output.R
- R/SS_readforecast.R
- R/SSplotComps.R
- R/SSplotSpawnrecruit.R
- R/getADMBHessian.R
- R/r4ss-package.R
- man/NegLogInt_Fn.Rd
- man/SSplotComps.Rd
- man/r4ss-package.Rd
A few bug fixes for rarely-used features that weren't yet tested. 
A few additional changes associated with the ongoing hake assessment.
Version now 1.30.1, dated Feb. 2, 2018.
> Merging development branch, increment version to 1.30.1 

- R/SS_output.R
Also dropped a for loop that can be avoided, could not resist ...
> Detect header line for Kobe, r4ss/r4ss#212

- DESCRIPTION
- R/SSMethod.TA1.8.R
- R/SS_output.R
- R/SS_plots.R
- R/SS_profile.R
- R/SS_readstarter.R
- R/SS_tune_comps.R
- R/SSplotBiology.R
- R/SSplotTimeseries.R
- R/r4ss-package.R
- man/SSMethod.TA1.8.Rd
- man/SS_plots.Rd
- man/SS_profile.Rd
- man/SS_tune_comps.Rd
- man/SSplotBiology.Rd
- man/r4ss-package.Rd
includes updates to work with SS version 3.30.12beta and other minor changes.
> merge Development

- R/SS_readctl_3.24.R
Argument ptype=TRUE controls if the PType column gets cbound to various data.frames in ctllist.
> Argument ptype=TRUE to select adding the PTYpe column, #253

- DESCRIPTION
- R/PinerPlot.R
- R/SSMethod.TA1.8.R
- R/SS_output.R
- R/SS_plots.R
- R/SS_profile.R
- R/SS_readctl.R
- R/SS_readctl_3.24.R
- R/SS_readctl_3.30.R
- R/SS_readdat_3.30.R
- R/SSplotBiology.R
- R/SSplotComps.R
- R/SSplotData.R
- R/SSplotNumbers.R
- R/SSplotProfile.R
- R/SSplotSpawnrecruit.R
- R/SSplotTags.R
- R/SSplotTimeseries.R
- R/r4ss-package.R
- man/PinerPlot.Rd
- man/SS_plots.Rd
- man/SS_profile.Rd
- man/SS_readctl.Rd
- man/SS_readctl_3.24.Rd
- man/SS_readctl_3.30.Rd
- man/SSplotData.Rd
- man/SSplotProfile.Rd
- man/SSplotSpawnrecruit.Rd
- man/r4ss-package.Rd
backlog of changes since early September, updates have been tested on 3.24, 3.30.12 and 3.30.13-beta models
> merge Development into Master

- R/SS_profile.R
- R/SSbiologytables.R
The SSbiologytables function writes csv tables for biology, selectivity, and retention as requested by Jim Hastie.
> Biology Table Function

- R/SS_readctl_3.30.R
All the variables are assumed to be preserved between two versions.
> Apply #262 to SS_readctl_3.30 as well

- .gitignore
- R/SS_RunJitter.R
- R/SS_output.R
- R/SSgetMCMC.R
- R/SSplotComparisons.R
- R/SSplotData.R
- R/SSplotPars.R
- R/SSsummarize.R
- man/SS_output.Rd
- man/SSgetMCMC.Rd
- man/SSplotComparisons.Rd
- man/SSplotPars.Rd
- tests/testthat/test_runs.R
- tests/testthat/test_simple.R
This includes the changes described here https://github.com/r4ss/r4ss/issues/257#issue-382895330. However, there's been no change to `mcmc.out` and `mcmc.nuisance` which produce MCMC diagnostic plots. Further consideration of changes to those functions will follow UW SAFS Think Tank presentation from Cole Monnahan on Feb 26.
> Merging mcmc_workflow branch into development

- R/SS_readctl_3.24.R
- R/SS_readctl_3.30.R
1. `N_CPUE_obs` length should be `Nfleet + Nsurveys`.
2. `fleetnames` should be stored in `ctllist`.
> Fix two bugs in SS_readctl(use_datlist = TRUE)

- R/SS_output.R
- R/SSsummarize.R
Adaptations for non-beta version of SSv3.30.13.00
> New column headers

- R/SS_profile.R
Small changes to SS_profile function:
1. Change a default value for model to match default value in function.
2, Also change so working directory always remains the same for the user regardless of when the function exits (on error, or completes).  Change inspired by code in ss3sim::ss3sim_base() (not sure how to give credit, sorry!)
> Development: fix working directory change in SS_profile

- R/SS_fitbiasramp.R
* Update r4ss::SS_fitbiasramp to work with 3.30 models
* Add some text-file output
> Biasramp3.30

- R/SSplotIndices.R
Merging branch associated with issue #325 to get `SSplotIndices` working for models with indices that don't have lognormal error structure.  The `SSplotIndices` function was extensively revised in the process. This has now been tested on a large set of models without any apparent issue so am now merging into 'development'.
> Non log indices

- R/SS_readctl_3.30.R
- R/SS_writectl_3.30.R
Small fixes, as noted here: https://github.com/r4ss/r4ss/issues/138#issuecomment-512586458 and https://github.com/r4ss/r4ss/issues/138#issuecomment-515111770. Also small changes in style and made verbose = FALSE actually not verbose. for SS_readctl_3.30.
> Fixes to SS_readctl_3.30 and SS_writectl_3.30

- R/SSexecutivesummary.r
- man/SSexecutivesummary.Rd
@chantelwetzel-noaa let me know if you'll have time to look through the changes which were associated with using this function for catch-only updates with an SS 3.24 model. Unfortunately I accidentally committed some of the reformatting changes (mostly indents and adding line breaks for extra-long lines) in the same commits as the substantive changes, so it's hard to look through the changes to see what the real differences are.
You can install the branch via 
`devtools::install_github('r4ss/r4ss', ref = 'SSexecutivesummary_changes')`
to confirm that the function still works for you.
> changes to SSexecutivesummary

- R/SS_readforecast.R
- R/SS_writeforecast.R
Completed update to 3.30 for all scenarios including catch caps and allocations. Also converted to match read_ctl format with element, vector, and dataframe add functions.
> Completed update to 3.30

- R/SS_readctl.R
- R/SS_readctl_3.30.R
- R/SS_readdat.R
- R/SS_readdat_3.30.R
- R/SS_writectl_3.30.R
- R/SS_writedat_3.30.R
This PR contains:
- Fixes in order to make it possible to read and write more complex control and data files using r4ss functions. In total, control files from 25 models were tested, many of which were production assessment models. Hopefully, this will expand the range of models that work with the r4ss read and write functions.
- Some formatting cleanup. This includes removing unnecessary comments, commented out code, whitespace, and also some formatting changes to headers to make the recognizable to rstudio as headers.
> Fixes for reading and writing control and data files from more complex models

- R/SS_readctl_3.30.R
Augment SS_readctl_3.30 to read the 2dAR selectivity parameters written
in the hake control file.
I did not create the dummy columns that were in the pseudo code previously
available.
Code still needs to be added to the write functions to handle these parameters.
Also, the internal function that I created might be better placed at the top of the read function. Not sure, but it was easier to read in the parameters using this internal function than the ones that were available.
I also have TMB code to estimate the parameters externally, but I am not sure where this code should be housed as it was provided in an email and requires TMB. Any ideas for how to store the code are welcome.
> feature: read in 2dAR selectivity parameters from control file

- R/SS_writewtatage.R
implemeted @kellijohnson-NOAA 's suggested approach
> Changed to make sink(split=verbose) argument

- R/SS_readctl_3.30.R
- R/SS_writectl_3.30.R
Small changes to PR #364 and #361. I will merge into development directly
> small changes to SS_writectl

- .Rbuildignore
- .gitignore
- R/SS_html.R
- R/SS_output.R
- R/SS_plots.R
- R/SSplotComps.R
- tests/testthat/test_simple.R
The main objectives of this PR are outlined in #367 .  Changes were also made to reduce output to the screen when verbose is FALSE.
> issue #367 - change .gitignore files, cleanup testing, reduce verbosity when verbose = FALSE 

- R/SSplotIndices.R
- man/SSplotIndices.Rd
> feat: add new index residual plots

- R/SS_output.R
- R/SSplotData.R
- R/SSplotSelex.R
Changes are related to issue #338, including new section in `SS_output()` which parses the deviation parameter labels for semi-parametric selectivity into a table and list of matrices and a new plot in `SSplotSelex()` (subplot 15) which represents that matrix of deviations. More detail to be provided on the issue page.
> Semi parametric selex plot

- R/SS_output.R
- R/SSplotAgeMatrix.R
- R/SSplotNumbers.R
- R/SSplotSelex.R
- R/SSplotSpawnrecruit.R
Small changes to get `SS_output` and `SS_plots` working with custom reporting options that will be available in SS 3.30.16. @iantaylor-NOAA, you know these functions much better than I do, so feel free to point out and make changes if the "fixes" were not done properly.
> fixes for custom reporting

- R/SS_output.R
- R/SSplotComparisons.R
- man/SSplotComparisons.Rd
- tests/testthat/test_simple.R
merge changes allowing SSplotComparisons() to automatically create comparison plots for all indices if the associated fleet numbers match across the models being compared as described at issue https://github.com/r4ss/r4ss/issues/105#issuecomment-653242942
> Default indices

- DESCRIPTION
- R/SS_output.R
- R/SS_readpar_3.30.R
- R/SSplotBiology.R
- R/SSplotPars.R
- R/SSplotTags.R
- R/SSplotTimeseries.R
- R/SSsummarize.R
- R/get_SIS_info.R
- R/r4ss-package.R
- man/SSplotPars.Rd
- man/get_SIS_info.Rd
- man/r4ss-package.Rd
- tests/testthat/test-simple.R
Includes a few bug fixes and minor additions that can now be available to anyone updating r4ss associated with the imminent release of Stock Synthesis version 3.30.16.00. 
Hopefully this version can also be submitted to CRAN next week unless further issues are discovered before then.
> merging recent changes from development into master

- R/get_SIS_info.R
Updated the values section of the function. 
Added the argument "Mgt_council." The default is "NA" and allows the function to work as it did originally for the NWFSC.  Mgt_Council ="GM" allows for Gulf of Mexico specific changes to values (e.g., a 3 year geometric mean for Best F).
> Added Gulf of Mexico specific features

- .Rbuildignore
- .travis.yml
- DESCRIPTION
- R/SS_output.R
- R/SS_plots.R
- R/SSplotBiology.R
- R/SSplotNumbers.R
- R/SSplotPars.R
- R/SSplotTimeseries.R
- R/SSsummarize.R
- R/get_SIS_info.R
- R/get_ncol.R
- R/r4ss-package.R
- cran-comments.md
- jenkins/Dockerfile
- jenkins/Jenkinsfile
- jenkins/run_r4ss.R
- man/SSplotNumbers.Rd
- man/SSplotPars.Rd
- man/SSsummarize.Rd
- man/get_SIS_info.Rd
- man/r4ss-package.Rd
CRAN submission is overdue (see notes at #206), so I'm hoping to submit tomorrow if there are no glaring issues in the current development branch, here merging into the master branch.
> merging changes over the past few weeks, prepping for CRAN submission

- R/SS_output.R
* Weird problem where "_" > 0 is TRUE
* Trailing space removed due to script automatically doing it (not related)
> Fix SS_output so that tests work for MSE

- R/SS_readdat_3.30.R
- R/SS_writedat_3.30.R
- tests/testthat/test-simple.R
See #493 . @iantaylor-NOAA , could you make sure this looks right when you have a chance?
> feat, issue #493: remove comp data lines with zeros

- jenkins/run_r4ss.R
@iantaylor-NOAA , this seems to be working consistently, so I think it would be good to merge into development? Thanks for figuring out this fix!
> Jenkins r4ss testing script 

- R/SS_changepars.R
- R/SS_profile.R
- man/SS_profile.Rd
Support added for multiple parameters.
This function tested in real-world application and example added to documentation.
I'll wait for tests to pass before merging pull request.
> feat(SS_profile): support profiling multiple parameters at once #224

- R/SS_plots.R
- R/SSplotYield.R
- man/SSplotYield.Rd
Suggestion from Michael Schirripa from back in April, finally merging into main branch now.
> add time series of YPR to SSplotYield()

- R/SS_readctl.R
- R/SS_readctl_3.30.R
- R/SS_writectl_3.30.R
Addresses #553  to allow reading and writing of new Stock Synthesis features.
> Read/write function changesahead of Stock Synthesis 3.30.18 release

- R/SS_Sensi_plot.R
- R/mcmc.out.R
- man/mcmc.out.Rd
These changes fix some warnings in r cmd check.
> Rcmdchk warnings

- R/SS_output.R
- R/SS_readforecast.R
- R/SS_writeforecast.R
- Adds MEY inputs to read/write forecast functions
- small fix for a reg ex needed due to changes in the report file
> Changes 3.30.19

- R/helper_fxns.R
- man/add_legend.Rd
I added arguments: 
legendloc, legendorder, legendcol, legendcex, legendsp, col, pch, lty, and lwd.
Also @export was added to save_png
> 617 add legend

- R/helper_fxns.R
Added filenameprefix argument to save_png, and type = "l" to add_legend
> Minor fixes to save_png fun and add_legend

- R/SSplotComparisons.R
- R/helper_fxns.R
Resolves line item request to replace r4ss::SSplotComparisons `legendfun` subfunction calls in with `add_legend` in helper_fxns.R  for #617
> 617 ssplotComparisons - add_legend

- R/SS_writewtatage.R
- R/check_inputlist.R
- R/check_model.R
- R/file_increment.R
- R/get_ncol.R
- man/SS_writewtatage.Rd
- man/check_inputlist.Rd
- man/check_model.Rd
- man/file_increment.Rd
I had a mix of Kelli Faye Johnson and Kelli F. Johnson. All instances of Kelli Faye Johnson have been changed to match the format of others where just a middle initial is provided.
> doc: Use Kelli F. Johnson

- R/check_inputlist.R
I noticed this when running tests that required the models folder. Changing this line fixed the tests locally. Note that looking at the extra r4ss tests log to see if all the testthat passed (I also noticed an issue where all the tests passing didn't fail the job) should ensure that this fix works.
> fix: check for wtatage file

- R/SS_output.R
- R/SSplotBiology.R
- R/SSplotComparisons.R
- R/SSplotMovementRates.R
- man/SSplotBiology.Rd
- man/SSplotMovementRates.Rd
Trying to plot results from this [two morphs model](https://github.com/nmfs-stock-synthesis/test-models/tree/main/models/two_morph) run with ss3.30.19 illuminated some issues (a missing space in the Report file, and issues creating plots when certain reported quantities aren't available. This PR provides fixes to allow `SS_plots()` to run.
> Fix two morph

- R/SS_readctl_3.30.R
- R/SS_writectl_3.30.R
This updates the read/write control file functions to incorporate the new Lorenzen M version that calculates M based on survivorship over a specified age range (issue #672). This pull request should not be merged until the feature is incorporated into SS3 (SS3 issue #328).
> Feature: Age-range based Lorenzen

- R/PinerPlot.R
- R/SS_parlines.R
- R/SS_varadjust.R
- R/SS_writectl.R
- R/SS_writectl_3.24.R
- R/SS_writectl_3.30.R
- R/SS_writedat.R
- R/SS_writedat_3.24.R
- R/SS_writedat_3.30.R
- R/SS_writeforecast.R
- R/SS_writestarter.R
- R/SSexecutivesummary.r
- R/SSplotAgeMatrix.R
- R/SSplotBiology.R
- R/SSplotComps.R
- R/SSplotData.R
- R/SSplotIndices.R
- R/SSplotNumbers.R
- R/SSplotProfile.R
- R/SSplotSexRatio.R
- R/SSplotSpawnrecruit.R
- R/bubble3.R
- R/copy_SS_inputs.R
- R/populate_multiple_folders.R
- man-roxygen/mainTitle.R
I added some more changes to the templating while I was reviewing it. @k-doering-NOAA can you check these then merge them in to your branch?
> More templates

- R/write_fwf4.r
This change allows to accept data.frame with factor column(s).
This recolve the problem mentioned in  #698
> type.convert factor column(s)

- .Rbuildignore
- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/library-scripts/common-debian.sh
Adds a .devcontainer based on the FIMS project, but without the C++ needs. Also downloads dependencies of r4ss in the dockerfile.
> Add .devcontainer to use r4ss in codespaces

- .gitignore
- DESCRIPTION
- R/SS_output.R
Added lines to only pull Length_comp_error_controls if the nrow > 0 for cases where there it is in the definition list but there is no info in the matrix.
> Partition weighting v3

- R/SS_readdat_3.30.R
- R/SS_writedat_3.30.R
- R/SSplotComps.R
These fixes to `SS_readdat()` and `SS_writedat()` were accidentally excluded from PR #766 (after I gave up on one branch and started a new one, I forgot to map them over.
Also the fix to #770 was accidentally added to this branch instead of "main" so simply merging the branch to get it into main.
> Partition weighting read write

- R/SS_output.R
- issue #830
- thanks @michellesculley
> fix SS_output() crash when NA in covar

- .github/workflows/r4ss-extra-tests.yml
fix this workflow to be reusable by adding workflow_call under on:
> add workflow_call to r4ss-extra-tests.yml

- tests/testthat/test-test-models.R
Not sure if it's working properly, but creating Pull Request to trigger github actions.
> Improving (hopefully) how the test-models get tested

- R/SS_output.R
- R/SS_plots.R
- R/SSplotIndices.R
- R/SSplotSPR.R
Minor changes to a few plots to meet the needs of the petrale assessment.
Recent changes are spread across too many branches, so merging this will help.
> Inspired by petrale

- .github/workflows/r4ss-extra-tests.yml
- R/NegLogInt_Fn.R
- R/check_exe.R
- R/get_ss3_exe.r
- R/jitter.R
- R/populate_multiple_folders.R
- R/profile.R
- R/retro.R
- R/run.R
- R/tune_comps.R
- man-roxygen/model.R
- man/NegLogInt_Fn.Rd
- man/check_exe.Rd
- man/jitter.Rd
- man/populate_multiple_folders.Rd
- man/profile.Rd
- man/retro.Rd
- man/run.Rd
- man/tune_comps.Rd
- tests/testthat/test-get_ss3_exe.R
- tests/testthat/test-profile.R
- tests/testthat/test-runs.R
- tests/testthat/test-test-models.R
- tests/testthat/test-tune_comps.R
- vignettes/r4ss-intro-vignette.Rmd
For some reason the SSplotComparisons isn't showing the 2nd subplot when I Knit the vignette so I had to grab the .png file to show the plot. If I do subplot = 2:3 it will show the 3rd one but not the second. However, when I knit the chunk in RStudio it shows the plots when running SSplotComparisons. It's so weird.
Please try this locally for you to see if it does the same thing when you Knit the vignette.
> update vignette with SSplotComparison plots

- R/SS_output.R
https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/513
> fix: add adjustment for new comment in Report.sso

- R/SS_output.R
- resolves issue #878
- relates to nmfs-stock-synthesis/stock-synthesis#500
> feat: add read of new "maximum_ASEL2" output #878

- R/SS_output.R
- R/SSplotComps.R
Fixes #898. 
The changes also include a revised warning associated with the .log file that was appearing for the test model that led to the plotting issue: https://github.com/nmfs-ost/ss3-test-models/tree/main/models/Simple_with_DM_sizefreq.
@e-perl-NOAA, the associated code is super confusing (I got lost numerous times), so don't feel obligated to track every detail, but if you seen anything obviously wrong, please flag it.
> Fix for D-M likelihood with size comp data.

- R/SS_recdevs.R
- man/SS_recdevs.Rd
- @e-perl-NOAA I think the change to the line following the new comment "split along all blank spaces, including tabs" should fix the issue you were having
> fix and cleanup to SS_recdevs()

- tests/testthat/test-test-models.R
Update test-test-models.R to run the models and SS_output in parallel and then test the results.
> Parallel test-test-models

- .github/workflows/call-doc-and-style-r.yml
- .github/workflows/r4ss-extra-tests.yml
- R/SS_output.R
- R/SS_readstarter.R
- R/SS_writestarter.R
- R/SSexecutivesummary.r
- R/SSplotSPR.R
- R/SSsummarize.R
- R/get_SIS_info.R
- man/SSplotSPR.Rd
- tests/testthat/test-populate_multiple_folders.R
See SS3 PR [#609](https://github.com/nmfs-ost/ss3-source-code/pull/609) for changes in SS3 report file that needed to be changed in r4ss.
> Fix spr series in SS_output() and get_SIS_info() to handle two table approach in SS3

- R/SSplotRecdist.R
Fix error seen in [this failed action](https://github.com/nmfs-ost/ss3-source-code/actions/runs/10256837962) from [this PR](https://github.com/nmfs-ost/ss3-source-code/pull/612) in the ss3-source-code repo to revise recr_dist output to show both sexes.
> Fix error in SSplotRecdist()

- R/SSplotCatch.R
- R/SSplotComps.R
- R/SSplotIndices.R
See issue #180
- Figure names with "." like TA1.8 changed to TA1-8
- Replace spaces in SSplotCatch figure names with underscore
- Remove spaces in SSplotIndices file names
> Change figure names in plots to have better latex compatibility

- R/SSplotProfile.R
- inst/WORDLIST
- man/SSplotProfile.Rd
Add if statements to create a label if a particular string is found in profile.string. See issue #919. This is a rather simple solution to quickly deal with the issue but open to suggestions if something else makes more sense.
I personally could not get case_when() to work. I don't think it could work on just one character value.
> Smarter profile.label for profile plots

- R/SS_writedat_3.30.R
- R/write_fwf4.r
fixes #952 in the simplest way possible by increasing the significant digits from 6 to 8.
> increase significant digits used in SS_writedat

- .github/workflows/call-r-cmd-check.yml
- .github/workflows/r4ss-extra-tests.yml
Hopefully this solution resolves the issue brought up in [this issue in the ghactions4r repo](https://github.com/nmfs-fish-tools/ghactions4r/issues/144#event-15156706350)
> add linux update lines to r4ss-extra-tests.yml

- R/get_ss3_exe.r
See [issue and resolution in gh package repository](https://github.com/r-lib/gh/issues/216). Resolves @efletcherPIFSC's [issue in ss3diags](https://github.com/PIFSCstockassessments/ss3diags/issues/109#issuecomment-2477541840).
> add token as NA to gh call in get_ss3_exe

- R/comp2long.R
- man/comp2long.Rd
- tests/testthat/test-comp2long.R
Hi, thanks for the positive feedback. I've added a testthat script for comp2long.
> Add test-comp2long

- R/table_compweight.R
- R/table_exec_summary.R
- R/table_ts.R
- man/table_compweight.Rd
@chantelwetzel-noaa, do you have time to take a quick look at these changes inspired by some things I noticed in our document as well as comments form Marlene on the submitted draft?
> Minor changes to captions for executive summary tables

- R/SS_output.R
- R/SS_readctl_3.30.R
- man/table_compweight.Rd
Follow-up on #1012 which failed more extended test of read functions for model that had use_rho = FALSE (I did local test with this model, but I guess not with final version of the function that I pushed).
> correction to parameter calc for 2D-AR (merged previous PR too quickly)

- R/SSplotBiology.R
- R/helper_fxns.R
Thanks to @chantelwetzel-noaa for inspiration to do this.
Now a command like 
`SS_plots(model, plot = 1, minyr = 2000, maxyr = 2025, pheight_tall = 3.5, pwidth = 6.5)`
will create plots of weight-at-age like those below that share the same scale making it more obvious that females and males have different growth.
> make scaling of weight-at-age plots shared across sexes

- R/SS_readctl_3.30.R
- R/SS_readforecast.R
- R/SS_readstarter.R
- R/SS_writectl_3.30.R
- R/SS_writeforecast.R
- R/SS_writestarter.R
- updated read and write ctl file
- updated read and write starter file
- updated read and write forecast file
See checklist in issue #941
> Fix read and write files for t-v biology and S-R curve a,b option

- .github/workflows/call-doc-and-style-r.yml
- R/SS_output.R
- R/SSplotData.R
- man/SSplotData.Rd
Closes #863 thanks to help from @MauroMardones.
Further refinements could be added later if needed.
> Add environmental data to SSplotData()

- R/SS_output.R
- R/SSplotYield.R
Revise SS_output() to work with changes in model output associated with in-development next version of SS3 (see https://github.com/nmfs-ost/ss3-source-code/pull/640)
> Read expanded stock-recruit output

- R/SS_output.R
- fixes #1048
- checks are passing so going ahead with merge for this simple change
- thanks @arni-magnusson!
> fix read of M_by_area table
