r4ss/r4ss

R/SS_html.R

In relation to issue #49, @taylori made change to name of model `Run_time`, to `RunTime`, and replaced old `Run_time` with `StartTime`. `SS_html.R` still referred to `Run_time` so returned NULL and left the HTML 'Home' page empty. This simple fix updates the reference for 'Starting time of model:' to the new `replist$StartTime`.
Suggest also that issue #49 can now be closed. :)

Update model 'StartTime' in SS_html

---

R/stackpoly.R

This fixes a bug in stackpoly that would give an error when you tried to make the plots with solid fill (instead of hashed). The ifelse() functions that were used before would give this error when x.hash was not specified: 'x' is NULL so the result will be NULL. This should fix that problem and allow for making both solid and hashed filled polygons.

stackpoly bug fix

---

R/SSplotData.R
man/SSplotData.Rd

I think this is ready to be implemented in master based on discussion in this commit: https://github.com/r4ss/r4ss/commit/2de27d95f2809392fdbb31794454832482cfe6a7#commitcomment-14227098
I've updated the branch to have circles be proportional to area instead of diameter and included a more informative HTML caption. Attached is a screen shot of the new plot in a browser.
@taylori If there's a set of models you use to test new functionality I could run this code by those. I've only tested this on two very similar models.

Add a second plot of model data that shows the relative precision within a data type

---

R/SS_output.R

This particular message could be hidden if hidewarn=TRUE. Probably some others too, but this one is hitting me right now.

Use hidewarn for 3.24f tag output warning

---

R/SS_readctl_3.24.R

The code I submitted a few days ago did not always work. This is, I think, better at detecting the number of rows in the age_selex blocks. I have only been able to test it with one dataset, happy to do so for others with blocks.

Improved detection of number of rows in selex blocks

---

R/SS_readctl_3.24.R

Code now looks for Block>0 in both `ctllist$age_selex_parms` and `ctllist$size_selex_parms`. #178

Counting blocks for both age and size selex when sizing ctllist$custom_sel_blk_setup

---

R/SS_readctl_3.24.R

The number of parameters for age selectivity pattern 17 depends on the 4th column ("Special") of `age_selex_types` matrix. See page 68–72 in "User Manual" version 3.24f.

Respect age_selex_types[,4] on pattern 17

---

R/SS_writectl_3.24.R

The column is added to `MG_parms` during `SS_readctl` process, and should not
be written to control files. Otherwise the roundtrip of read-write
is impossible.
https://github.com/r4ss/r4ss/blob/871255ec83022df6594225a308c37c15d6da0c6d/R/SS_readctl_3.24.R#L481-L482

Exclude PType column from MG_parms in SS_writectl output

---

R/SS_readctl_3.24.R
R/SS_readctl_3.30.R

`paste0()` with `sep=` argument works in an unexpected way. E.g., `paste0('a', 'b', 'c', sep=',')` ends in `'abc '`, not `'a b c'`. Duplication in lambda table has been checked with the strings concatenated by paste0, and it can result in false positive. E.g., rows (1,20,1,1,0) and (12,0,1,1,0) get marked duplicated.

Fix duplication check in SS_readctl

---

R/SS_profile.R

Tested and SS models ran for both relative and absolute specifications for dir with this change. Before, models would not run if a relative dir was used.

Fix so a relative path for function input dir can be used with function SS_profile().

---

R/SS_readforecast.R
R/SS_writeforecast.R

If mylist$Flimitfraction is negative, a matrix of years and limits
will follow Flimitfraction. I use -999 to find the end of the matrix.
Then, many i values are skipped over so that the matrix values are not
wrongly put into other named values.
The write forecast function then puts writes these numbers back to the
file if Flimitfraction is negative.
I don't predict that the changes will have any conflicts with other
versions of SS.

fix: allow for matrix of Flimitfractions in forecast

---

R/SS_readdat.R

Two fixes were made here: 1) change the function version input to NULL to try to always try to read the version, and 2) modify the catch field reading and writing to account for equilibrium catch.

Correction to read the version number and also handle equilibrium catch

---

R/SS_readctl.R
R/SS_readctl_3.24.R
R/SS_readctl_3.30.R
man/SS_readctl.Rd
man/SS_readctl_3.30.Rd

This change fixes issues with reading the number of recruitment distribution params read in  MGparms, which varies by method. Also adds warnings when using recruitment distribution method 1 or recruitment method interactions, which should not be used in 3.30 but were possible to use  in early versions of SS 3.30. Finally, it cleans up some inconsistencies among the functions in terms of how variables are named.
It includes a fix to allow the control file to be read when no variance adjustment was used, but this was taken care of by @lee-qi in commit c9feed80892a7d94cab2e8ca0489c38ad69d7049 that is now incorporated in master and development branches.
Note that I created this branch off an older version of development (last commit fae607a1c3c63a78b20714dce9e492b5b60e7f5f), which is why it …

Edit readctl

---

R/SS_readdat_3.30.R
R/SS_writedat_3.30.R

Bycatch only fleet info previously was being grouped in incorrectly as catch data in the SS_read/write_3.30 functions.This now allows it to be read and written in the correct format.
Testing done on a model with several bycatch only fleets as well as a model without.
Please feel free to change column or variable names if desired. I tried to use terms from ```data .ss_new``` 3.30.13 default comments when feasible.

Fix: Add bycatch only fleet to SS_read/write_3.30 funs

---

R/SS_changepars.R
R/SS_parlines.R
tests/testthat/test_profile.R

Development in SS_parlines and SS_changepars. I think they are all okay, given they pass the new tests that I made, but (3) could be thought about more and better developed to work with (4).
(1) SS_parlines object ncols was not large enough for sablefish model, now it dynamically creates a large enough matrix.
(2) SS_parlines interpreted blocks_per_pattern as a parameter
(3) SS_changepars would reorder parameter names if unique() removed duplicated names causing the newvals to be out of order with the names. My changes here could potentially be further developed, but at least they remove the error that I found. Unfortunately, they still don't work if you want to use repeat.vals = TRUE and give it a vector of the same length as strings but have each individual string match multiple …

Fix changepars

---

R/SS_readforecast.R
R/SS_writeforecast.R

I wrote a line into SS_readforecast which can deal with fleet_relative_F == 2 (retaining the correct order of mylist) and disabled the attendant stop() in SS_writeforecast . Worked reliably on my china rockfish iterations.

enable read/write_forecast with fleet_relative_F == 2

---

R/SS_writectl_3.30.R

Small fix. Adds terminator line to output SS file when N_lambdas = 0 and also checks for input consistency. ran test-control testthat() automated tests, and read in/out ctl files with and w/o lambdas in the file.
Note I did not run devtools::check() locally b/c the changes were so minimal.

Fix for SS_writectl_3.30()  when N_lambdas = 0

---

R/SSplotRecdevs.R
R/SSplotTimeseries.R

2 observed problems
(1) using minyr in SSplotRecdevs was leading to the wrong years being plotted b/c it was subsetting the time series twice with goodyrs
(2) the ylim of SSplotTimeSeries(subplot = 11, minyr = x) was very large when I used the minyr argument, which was occurring because stdtable was not being truncated for the same years as the time series
I am pretty sure that I fixed (1), but the fix to (2) might not be the best. SSplotTimeSeries is more complicated and so I may have introduced problems for other things. I can easily revert this last commit and repush if you think that (2) should be fixed a different way and you just want to merge in the fixes for (1).

Fix years plotted in rec deviations and ymax in recruitment time series

---

R/SS_output.R

"Natural_Morality" is a section of the report file where the
natural mortality value is specified per age. This output is
potentially different than the temporal Z at age matrix where
there is no value for the terminal age category and the next to
last age category is an approximation.
I also read in the M_type now as a list element.
This is needed for Claudio Castillo-Jordan's work.
I tried to match the code below for the growth parameters. 
Checked with devtools::check() with 0,0,0 notes, warnings, and errors.
Not entirely sure if this will break with older models because I only
checked it with 3.30.14.

feat(M_type): SS_ouput now reads M parameter and type

---

R/SS_fitbiasramp.R
R/SSplotAgeMatrix.R
R/SSplotPars.R
man-roxygen/cex.main.R
man-roxygen/methot2011cjfas.R
man-roxygen/pheight.R
man-roxygen/ptsize.R
man-roxygen/punits.R
man-roxygen/pwidth.R
man-roxygen/res.R
man/SS_fitbiasramp.Rd
man/SSplotAgeMatrix.Rd
man/SSplotPars.Rd

SS_fitbiasramp was verbose even when verbose = FALSE and the output to the screen was clogging up ss3sim, which led to additional changes to the function to try and incrementally clean a few things up. Pull request includes
1. fix up documentation from development to pass CRAN checks
2. add verbose in front of cat()
3. start using templates more in documentation, add some more info to SS_fitbiasramp
4. more templates for arguments, these can be carried forward to other functions, but figured that would be better done directly in the development branch than here
5. remove code that was commented out in SS_fitbiasramp

Biasadjust

---

.travis.yml
README.md

We need to see if this works on travis first. Then, @iantaylor-NOAA, if you make an account at https://codecov.io/gh to use with your github account, we should be able to add the badge to the repo.

add codecov to travis - first attempt

---

R/SS_readdat_3.30.R

It was looking for 999 without anything following it, but some users may have a comment after the 999. Using \\b finds the whole word. Tested with this code:
`tmp <- c("999 # End of data file","999","999#","xx","9999","99","999\t")`
`grep("^999$",tmp)`
`grep("\\b999\\b",tmp)`

update SS-readdat_3.30.R to find 999 EOF marker

---

R/SS_writewtatage.R

`print.data.frame()` defaults to writing `getOptions("maxOut")`, so the longer weight-at-age file I was trying to write was coming out with the standard R output:  `[ reached 'max' / getOption("max.print") -- omitted 662 rows ]`
I fixed it for my case by setting `print.data.frame(max=dim(mylist)[1]*dim(mylist)[2]` but there might be a more elegant solution.

Added argument print.data.frame() in SS_writeatage

---

R/SS_output.R
R/SS_tune_comps.R
man/SS_tune_comps.Rd
man/SSexecutivesummary.Rd

Small changes to reduce verbosity in `SS_output` and `SS_tune_comps`, if the user desires. The motivation for this was using some functions in ss3sim and wanting to have the ability to reduce output to the console. The biggest change is adding an argument `verbose` to `SS_tune_comps` which has a default value of TRUE, I also ran `devtools::document()` .

Reduce verbose

---

R/SSplotComparisons.R

Problem = indices are not subset for endyr like other matrices. The hake assessment uses a group plot of five different comparisons (e.g., biomass, depletion, index) for bridging models and the different terminal year for the panels was driving Chris crazy. 
* truncate indices by endyrvec
* change the limit of the xaxis given the newly truncated
values or keep range if there is no endyrvec
* make the axes values pretty b/c lots overlap when you have
four digit year values with las = whatever makes the x axis parallel
One issue that I did not deal with because I am not sure how to, is the padding on the x axis. Other plots remove this padding automatically, but it makes it awkward with the index value because without the padding you cannot see the points at the min and max years very well. …

fix indices plot in SSplotComparisons

---

R/SS_readctl.R
R/SS_readctl_3.30.R
R/SS_readdat.R
R/SS_readdat_2.00.R
R/SS_readdat_3.00.R
R/SS_readdat_3.24.R
R/SS_readdat_3.30.R
R/SS_writectl_3.30.R
R/SS_writedat_3.30.R
man/SS_readctl.Rd
man/SS_readctl_3.30.Rd
tests/testthat/test-control.R

Moved all code out of read/write wrapper files and into version specific functions. Unified variable names between data and control read/write with previous versions to avoid any compatibility issues. Also fixed a small bug in SR_parms in readctl_3.30 that had naming errors. (Note: naming convention issues with nseas, N_areas, and Ngenders remain but can be addressed in a later commit when we decide on a best option moving forward)

fix: Consolidate code into version specific read/write files

---

R/SS_readpar_3.30.R
R/SS_writectl_3.30.R
R/SS_writepar_3.30.R

Fix a variable name issue in SS_readpar_3.30 and fix file overwrite function in control and par file writing functions for 3.30.

fix: readpar variable names write ctl overwrite

---

R/SS_writeforecast.R

Fixed a bug that tried write allocation among groups as a data frame instead of a vector when using SS 3.24

Fix: allocation among groups bug

---

R/SSMethod.Cond.TA1.8.R
R/SSMethod.TA1.8.R
R/SS_output.R
R/SS_plots.R
R/SS_tune_comps.R
R/SSplotBiology.R
R/SSplotComps.R
R/SSplotData.R
R/make_multifig_sexratio.R

Merging a branch which includes changes related to the following elements of the upcoming release of SS version 3.30.15 which has changes in the output related to length and age composition data including:
- sample size column `N` in tables within Report.sso and CompReport.sso replaced by `Nsamp_adj` and a new `Nsamp_in` column showing the unadjusted input sample size has been added
- a new `Nsamp_DM` table has been added to the `FIT_AGE_COMPS` table (`$age_comp_fit_table`) and corresponding tables for length comps showing the estimated sample size associated with the Dirichlet-Multinomial likelihood. These values aren't yet being utilized in the figures to replace the internal calculations discussed at https://github.com/r4ss/r4ss/issues/129.
The tables with names like …

Revised comp output

---

R/SS_readpar_3.30.R

Update to prevent error in number of F_rate and F_init pars read which crashed under some circumstances. Sometimes SS creates F pars for zero catch years and sometimes it doesn't.

fix: reading number of F_rate and F_init parameters

---

R/SS_readctl_3.24.R
R/SS_readctl_3.30.R
R/SS_writectl_3.24.R

Thanks to @nklaer for suggesting these modifications. They include:
- reducing verbosity when `verbose = FALSE` in `SS_readctl_3.24` 
- renaming the list component of output from `SS_readctl_3.24` containing the SR parameters from SRparm to SR_Parms (to mirror the names in `SS_readctl_3.30`). Note this is a breaking change, but partial matching could be used to access either name (e.g., `ctllist$SR` would access the old or new names via partial matching, although this could potentially match other list components that include SR in their name). SS_writectl_3.24 also assumes this new name, `SR_Parms`.
- fixes in `SS_readctl_3.30`: the MG parameter count, accounting for datalist using `Ngenders = -1`
- fixes in `SS_readctl_3.24` for reading selectivity, seasonal effects, reading fecundity …

Improvements and fixes to read and write control file functions

---

R/SS_readctl_3.24.R
R/SS_writectl_3.24.R
R/SSplotComparisons.R

Includes fixes and improvements to `SS_readctl_3.24()` and `SS_writectl_3.24()`. Note that users should access these functions by calling `SS_readctl()` and `SS_writectl()`.
Fixes include:
- Ability to read and write the MG env var short parameter lines
- write all par lines for growth model option 3
Improvements include:
- `SS_writectl_3.24()` writes `#v3.24` at the top of the file
- style changes to code to make it more readable and consistent
- slight refactoring to remove an unused object `Age_K_count` in `SS_readctl_3.24`

Fixes and improve SS_readctl_3.24

---

R/SS_output.R

I have a simulation EM that only has one era, i.e., no early rec devs,
and SS_output was failing b/c the colnames were off by one row in rmse_table.
Now, the code checks that the appropriate last_row_index is being used by
removing column names from the rmse_table and checking that the header
row is in raw_recruits.
I am not sure if these if statements are the best way to implement this fix or if
legacy SS models will not be compatible with my thinking.

Fix(SS_output): when rmse_table only has one era

---

R/SS_readstarter.R
R/SS_writestarter.R
tests/testthat/test_simple.R

This development is for a custom reporting feature (detailed output option = 3) to come in the 3.30.16 release of Stock Synthesis. It allows the setup in the starter file to be read in and written out. These changes were tested locally on models that use and don't use the custom reporting feature.

Read and write custom reporting options in starter file

---

R/SS_output.R

I am not sure why development is currently passing because I found the error
when running check() on development.
* Copied code from agentune that changed _ to NA so type.convert can
change all values to numeric ones for mathematical operations.
* I did not remove these rows of NA as is done in agentune.
* future development should work to include a function to process the tuning
information, this new internal function could be used to process each each tuning section rather than
have code that is duplicated for the two sections.

fix(SS_output): lenntune had non-numeric values of _ for fleet 3

---

R/SS_output.R

headers were being created from the first row when they are already being pulled in matchfun2. Thanks to Dan Fu for reporting this bug (https://vlab.ncep.noaa.gov/web/stock-synthesis/public-forums/-/message_boards/view_message/11095850)
@iantaylor-NOAA could you make sure this change looks ok and merge in if so?

fix: movement in ss_output

---

vignettes/r4ss-intro-vignette.Rmd

Functions to edit stock synthesis input files with R (the `SS_read*` and `SS_write*` functions) as well as functions to run Stock Synthesis models have evolved to a point where they could see routine use. As acknowledged (for some functions) in #430 , they have not been well advertised. Including examples of their use in the `r4ss` vignette may increase users' awareness of these functions.
@iantaylor-NOAA (or anyone else interested), please feel free to edit these changes if you see improvements!

docs: expand vignette to include scripting workflow

---

R/SS_tune_comps.R
R/run_SS_models.R
tests/testthat/test-tune_comps.R

This PR partially addresses #430 by allowing relative paths to the executable in `run_SS_models`. It also adds some additional checks on where the exe is located. Note, however, it is not perfect; The biggest issue I'm not sure how to fix is that if you wanted to use an exe called "ss.exe" in each model folder specified in dirvec, but ss.exe was also in the user's PATH (environmental variables) , the PATH version would be used by default even if `exe_in_path = FALSE`.  I have added a warning when this happens, but there may be a cleaner solution (for example, maybe we don't really need the `exe_in_path` argument at all?
This also includes a fix to a check on the `fleets` argument in `SS_tune_comps` that wasn't working properly.

Allow relative path to exe in run_SS_models, fix to check in SS_tune_comps

---

R/SSplotComparisons.R

Fix small bug which prevented uncertainty in the indices from being plotted in `SSPlotComparisons`.

Fix small bug in SSPlotComparisons fits to index

---

R/SS_tune_comps.R
man/SS_tune_comps.Rd

QUESTIONS: 
* can someone check my proposed math in this commit to
ensure that I got the tuning correct?
* also, now that I created the pull request I remembered that
I only tested this with age comps; can someone check that I didn't
break things for length comps?
recommended variance adjustment is wrong b/c it was set to 1.0.
@iantaylor-noaa knows and is fixing it in SS but r4ss will still
need to work with this output for 12-16 models.
Updated documentation based on ability to use markdown in the file,
which makes things easier to read, moved some sections.
Noticed during the 2021 pacific hake stock assessment

fix(SS_tune_comps): MI_mult for agecomps is wrong in SS 3.30.12-16

---

R/SS_readdat_3.30.R
R/SS_tune_comps.R
R/run_SS_models.R

Working with ss3sim that uses SS_tune_comps to reweight data behind the scenes, I am trying to limit the output that is printed to the screen if verbose = FALSE. Which led to two things
1. SS_tune_comps() reads in report files with SS_output multiple times without setting covar = FALSE or TRUE. This is okay, but I put in a check to see if you for sure are not running with the hessian then do not try to have covar = TRUE. This essentially doesn't change anything. I did note that if you set covar = FALSE and you do have the hessian, that the results of Francis low and Francis hi will be different. Should we not be reporting these values if there is no hessian? Doesn't matter for weighting though.
2. show.output.on.console = FALSE stops admb output from being printed to the screen. I know …

Killoutput

---

R/SS_readctl_3.30.R
R/SSplotTimeseries.R

Subplot=11 (Total recruitment time series) in SSplotTimeSeries has a bug if there is multiple areas .  This commit fix this.
Also SS_readctl_3.30 is improved on the label(rownames) of time vary parameters for time block. Now it reflects block function (column 14 of parameter).  Previously "add" is always used regardless of block function used.

Fix subplot=11 of SSplotTimeSeries and improve label of time block parameters of SS_readctl_3.30 

---

R/SSsummarize.R

new row in pars, parSD, and parphases
* write a helper function copy.dm, where the DM parameters that were named
EffN_mult are copied into the rows for the DM_theta parameter which will be in
newer models; nothing is changed in the EffN_mult line, this is to encourage people to
use the new naming rather than leaving their code as is with EffN.
* name parphases with model names as is done for the other "par" data frames;
I looked back in the code and this line had not been touched other than line endings
for over 10 years and I am guessing it is just that no one uses this table that
has led to the names staying V1 V2 ... instead of model1 model2.
* make a few if(verbose) checks to limit output to the screen.
pushing to branch to run automated tests prior to merging in, but I don't see
any …

fix(SSsummarize): DM parameters have a new name (DM_theta);

---

README.md

This pull request is to add a section on contributing in the readme and a code of conduct to the r4ss project (see the change to learn more about the contents of the contributing guide and the code of conduct). 
These are preliminary versions that can be changed. Please feel free to comment on this pull request or email nmfs.stock.synthesis@noaa.gov or the maintainer (which can be found by running `maintainer("r4ss")` in R) with your suggestions. Perhaps this can be left open at least a week for comments? I think changes could still be incorporated after that time, though.

docs, init: add contributing info and code of conduct to r4ss

---

R/SS_readdat_3.30.R

4th column of fleet_info indicates if catch multiplier is to be used by setting this column to 1.  Catch multiplier can only be used for catch fleets. However SS_readdat_3.30 does not check if 4th column is 1 for fleets other than catch fleets. In the case of SS, it stop reading datfile if 4th column of fleet_info is 1 for non-catch fleets. This PR add similar error check for 4th column of fleet_info.

Add error check for need_catch_mult in fleet_info

---

R/SSplotIndices.R

@taylori this really simple change is a pull request for you because you were the one that worked with #326 and #324. Sablefish models are still running into errors and I tracked the latest one down to this where `index_resids.fn` doesn't play nice with the normal distribution.
@mkapur this fix should fix the error you were having with building the pdf.

More for #324 sablefish environmental index in figures.

---

R/SS_readctl_3.30.R
R/SS_readdat_3.30.R

- SS_readctl_3.30 can now read time varying trends. Before, would exit on error with a confusing warning.
- fix: SS_readctl_3.30 correctly reads the number of parameters for env link option 4, which requires 2 short parameter lines, not 1 like the other options.
- feat: adds a warning to SS_readdat_3.30 if the data file does not have consecutively numbered Dirichlet Multinomial parameters starting from 0. SS will exit on error while reading input files, but warning instead of error allows  users to fix this within the list read in using SS_readdat.
- fix: A check that there are no lines of all 0 length comps errors out when there are no length comp lines. Adds in a fix so this check is skipped if there are no lines.

allow SS_readctl_3.30 to read tv trends, small fixes

---

R/SSmohnsrho.R

Ive made the following changes to the calculations:
1. Previous Mohn's rho calculation for the original (option 1) and Woods-Hole (option 2) types were off by one year. The value for the first peel was calculated as the relative difference at the terminal year of the base model, and the value for the second peel was calculated as the relative difference at the terminal year of the first peel, and so on. Thus, Mohn's rho for a 5 year retrospective from from a base model ending in 2020 was calculated from the differences at 2020-2016. The differences should be calculated at 2019-2015. 
My fix was to add "+1" to the index of the endyrvec when calculating the original and Woods-Hole Mohn's rho. 
2. The Woods-Hole rho calculations only calculated the differences among years where data was …

Update scripts in SSmohnsrho

---

R/SS_readctl.R
R/SS_readctl_3.30.R
man/SS_readctl.Rd
man/SS_readctl_3.30.Rd

Fixes an assumption in SS_readctl about how many lines of tagging params to read in 3.30. It should only be a parameter for each fleet of type 1 or type 2  ONLY( not including survey fleets).

fix: number of tag pars to read in ctl file

---

R/helper_fxns.R

close #592 using dir(pattern) and ifelse
The pattern matching is done with `[e]*[c]*[h]*[o]*` which means 0+ instances of those characters in square brackets. Thanks to @k-doering-NOAA for mentioning what happens when the length of the match is nothing. The call to `tail()` is still fine because it returns `character(0)` and the `ifelse()` call changes it to `NA`. The `tail()` is needed in case both data.ss_new and data_echo.ss_new both exist. The returned value is alphabetized so the latter, which is the newer file, would always be the last value.

fix(get_dat_new_name): if was changing to NA

---

.github/workflows/call-calc-coverage.yml
.github/workflows/call-doc-and-style-r.yml
.github/workflows/call-r-cmd-check.yml

Reusable workflows now in https://github.com/nmfs-fish-tools/ghactions4r
Thanks for the reminder in #598 , @iantaylor-NOAA !

change path to reusable workflows

---

R/SS_output.R

Somewhere in new changes with SS, the ss.log file has the 'size' rows appearing on different line numbers. This removes hard-coded line numbers and does a regexp match on lines that begin with 'size'. There is also now an error message if these rows are not found.

Fix a bug reading in ss.log

---

.github/workflows/call-r-cmd-check.yml

This add back in tests that require an executable and model files. This used to be part of the rcmdcheck workflow, but was removed since it was only need by r4ss and we wanted the rcmdcheck workflow to be generic to all r pkgs. Now, there is a separate reusable workflow referenced that runs these tests for r4ss.

test: Add back the r4ss tests that require an exe and models

---

DESCRIPTION
NEWS.md
R/SS_output.R
R/SS_profile.R
R/SS_readctl.R
R/SS_readdat.R
R/SS_readforecast.R
R/SS_varadjust.R
R/SS_writectl.R
man-roxygen/version.R
tests/testthat/test-control.R

Standardize the input argument `version = "3.30"` rather than having some use the `NULL` option.
I am not sure if the third commit that removes checks for `NULL` should be left in. I purposefully made it the last commit and separated it from everything else such that we can easily remove the commit from this pull request.
I did **NOT** find `version = NULL` in any of the tests, nor did I write any tests 👎 😢  One additional thing to think about is your request in #641 to update the check to see if the version in the list matches the argument. I have not addressed this as of yet, which is why this is just a draft. I think I will just make a stop() call if the values do not match. Let me know if you do not agree.

Fix argversion

---

.github/workflows/call-calc-coverage.yml
.github/workflows/call-r4ss-extras-codecov.yml

Addresses #645
As discussed in https://github.com/r4ss/r4ss/issues/574#issuecomment-1087962225 , code coverage is currently not accurate, because there are tests in r4ss that rely on executables and models. This adds a workflow where the ss3 exes and model files are downloaded before calculating code coverage to improve the accuracy.
Note this also switches to using ubuntu instead of osx to run the job; I think this should work fine, but if it doesn't we can switch the github runner to osx.

gha: calculate more accurate code coverage

---

R/SS_read.R

The change I made is only one line in SS_read.R
```
if (ss_new) {
datname <- "data.ss_new"
```
is changed to use get_dat_new_name 
```
if (ss_new) {
datname <- get_dat_new_name(dir)
```
This change allow SS_read function to work with SS3.30.19* with ss_new=T
I only tested with the case starter$N_bootstraps =2. If it is not 2, some additional care might be needed.

fix SS_read.R for SS3.30.19 with ss_new=T

---

.Rbuildignore
.covrignore
R/SS_doRetro.R
R/SSmohnsrho.R
R/copy_SS_inputs.R
R/getADMBHessian.R
tests/testthat/test-TSCplot.R
tests/testthat/test-plotCI.R
tests/testthat/test-populate_multiple_folders.R
tests/testthat/test-runs.R

Related to #316 (note this issue was closed a while ago because it is open-ended and not helpful).
While looking at codecov.io for r4ss, I realized there were a number of files that don't have any coverage at all. I attempted to add tests for some of these functions that I know get use.
This PR should increase code coverage, for the functions `SS_mohnsrho`, `getADMBHessian`, `TSCplot`, `plotCI`, and `populate_multiple_folders`. 
I also made some changes to functions and documentation as noticed while working on adding these tests. In particular, there was an issue with the Mohn's rho calculation where the necessary output was not available. I added a check for this and skipped the particular calculations, but there may be a smarter way of dealing with this problem.

Improve codecov by adding tests for functions that don't have any

---

R/SS_writedat_3.30.R

Users might erroneously have `d[["use_MeanSize_at_Age_obs"]] == 1`
when there are no observations. This happened to me in a
simulation when prior to sampling I had mean size, then
after sampling the data frame was NULL.
Thus, the new check ensures that the observations are not NULL
and if they are, then it sets d[["use_MeanSize_at_Age_obs"]] to 0.
@k-doering-NOAA did I use the `&&` appropriately here or should it be `&`?

fix(SS_writedat_3.30): Adds check for no mean size

---

DESCRIPTION
R/SS_read.R
R/SS_readstarter.R
R/SS_readwtatage.R
tests/testthat/test-readwrite.R

Had to rework the check for non-existent files or files without any information in `SS_readstarter()` and `SS_readwtatage()` to accommodate a URL yet would still return `NULL` in the latter function when appropriate.
* Allows for a URL to `SS_read(dir=)`, which facilitates using `users-examples` in the Stock Synthesis organization.
* Increases documentation of `SS_read` functions by adding an example with weight-at-age data and providing some detailed information about `SS_readstarter()` that might be helpful to new users.
* Uses @template verbose instead of bespoke text.
* Adds `mustWork = FALSE` to normalize path because a URL will lead to a warning.
* Adds test using a URL
* Fixes formatting of line length and a few other minor formatting issues.

677 `SS_read()` allows a url

---

R/SS_readdat.R
R/SS_readdat_2.00.R
R/SS_readdat_3.00.R
R/SS_readdat_3.24.R
R/SS_readdat_3.30.R
tests/testthat/test-simple.R

Addresses #678. Also extends work done in #671, which included deprecating unneeded arguments in the read/write functions. For some reason, the echoall argument was not removed from the SS_readdat* functions, so it is done in this pull request

Remove faster from tests; deprecate echoall argument in SS_readdat* functions

---

R/SS_read.R
R/SS_readpar_3.30.R
R/SS_write.R
man/SS_read.Rd
man/SS_write.Rd

This pull request addresses issue #681 and is now passing all tests. Corrections have been made to the read_par function to include 2DAR dev parameters and to the SS_read and SS_write functions to include the ss.par file if it is present.

Test readwrite par

---

R/SS_output.R
R/SSbiologytables.R
R/SSplotBiology.R

Header in BIOLOGY table in Report.sso is being revised along with changes to the content of that table for models that don't include length-based maturity or fecundity.
See https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/348 for details.
This PR updates to the new names for all earlier Stock Synthesis versions as well. Merging these changes will facilitate testing the SS3 changes without making the workflow grab an r4ss branch.

refactor: update names in BIOLOGY table

---

R/SS_output.R
R/SS_plots.R
R/SS_readctl_3.30.R
R/SS_readdat_3.30.R
R/SS_writectl_3.30.R
R/SS_writedat_3.30.R
R/tune_comps.R
inst/WORDLIST
man/SS_plots.Rd
man/tune_comps.Rd

This PR resolves issue #735, where changes in the input and output of the Dirichlet-multinomial setup were required to prepare for the Multivariate-Tweedie distribution and resolve some inconsistencies in the current implementation. DM likelihood is now available for generalized size comp data as well. More detail on the changes is provided in https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/357 and the issues linked from there (associated with the ["Epic: Data weighting improvement" label](https://github.com/nmfs-stock-synthesis/stock-synthesis/labels/Epic%3A%20Data%20weighting%20improvement)).
Changes to `SS_output()` include some re-ordering unrelated to this issue to make things more logical.

Dirichlet-multinomial changes

---

R/SSplotSpawnrecruit.R

This is in response to the failed checks on [this ss pull request](https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/384). The SSplotSpawnrecruit.R file was changed to add "if (is.null(replist[["SpawnOutputUnits"]]) ||" on line 110. This says that it's 9 commits ahead of main but it's really just one - I was struggling to change the commit message and also changed the name of the branch.

Ss3 pull request 384 fix

---

R/SSplotComps.R
R/SSplotData.R

Simple change to avoid confusion with ghost gear (https://oceanservice.noaa.gov/facts/ghostfishing.html) or IUU fishing as discussed by NWFSC and SWFSC assessment teams here: https://github.com/pfmc-assessments/PEPtools/issues/26.

change "Ghost" to "Excluded" in legends & captions

---

R/SS_output.R

Fixes issue #785.
Thanks to @chantelwetzel-noaa, I figured out that this is an issue with the SS3 output as noted here: https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/435.

fix: work-around for duplicated unsexed comps

---

R/copy_SS_inputs.R
man/copy_SS_inputs.Rd

Small trivial changes to copy_SS_inputs where
* return of logical, TRUE or FALSE, is now invisible so users do not have to assign the function call to a dummy object to suppress the output 
* updated some documentation spacing and added a full stop to the end of an explanation
* updated the documentation for the recursive argument because I didn't understand what it was doing
* added an example that all users can run on their machine
@iantaylor-NOAA I added you as a reviewer to merge this in but you shouldn't actually have to review anything, pretty simple changes I mainly just wanted GitHub actions to run through the checks first before bringing it in to main.

Invisible return of logical from `copy_SS_inputs()`

---

R/SSmohnsrho.R
inst/WORDLIST
man/SSmohnsrho.Rd

Thanks to @chantelwetzel-noaa for noticing that the {r4ss} end year of the model is really the end year of the data and that we need to have retrospective calculations related to biomass be end year of the model + 1 because we want to report end of year biomass, where Stock Synthesis calculates beginning of the year biomass. Fishing mortality ($F$) is still based on the end year of the model but all other quantities are now end year + 1. {nwfscDiags} will work just fine as is with these changes. If users actually want to compare the "updated" output with previous calculations they could run the function twice with different inputs to endyrvec.
Commit summary that I believe should be brought in as three separate commits rather than squashed and merged:
1. Reformatted old documentation
2. …

Fix retro to use endyr + 1 for biomass-based quantities

---

DESCRIPTION
R/SS_output.R
R/SSgetoutput.R
R/SSplotBiology.R
R/SSplotComps.R
R/jitter.R
R/make_multifig.R
inst/WORDLIST
man/SSplotComps.Rd
man/make_multifig.Rd

- Avoids bad sigmaR tuning value (#823) (now reports "needs_Hessian" instead of misleading value).
- Fixes issue with plot of length-based maturity option 6 converted to age (line was missing from biology plots)
- Applies `verbose` argument to recently-added message about duplicated samples
- Fixes spelling error
- Improves code formatting

Assorted cleanup

---

R/SSplotComps.R

- fleet 10 came before fleet 2 in models with more than 9 fleets with comp data, now fixed
- thanks @brianlangseth-NOAA for flagging this

fix for aggregated plots in alphabetical rather than numeric order

---

R/get_ss3_exe.r
man/SSplotSPR.Rd
man/get_ss3_exe.Rd

Go back to return() instead of message() for where exe is downloaded.
@iantaylor-NOAA I ran devtools::document() and the man/SSplotSPR.Rd changed, I guess you did updates to the R file recently? Can you double check that this is right?
Resolves #852

Use return instead of message for get_ss3_exe

---

R/SStableComparisons.R

There was an error related to missing `SpawnOutputUnits` when comparing models which used empirical weight-at-age but had no comp data. This should allow the comparisons to go forward.

fix error when comparing EWAA models with no comps

---

R/jitter.R
tests/testthat/test-runs.R

It turns out that
```
future_map(x, ~my_func(.x, ...))
```
Is not the same as:
```
future_map(x, function(.x) my_func(.x, ...))
```
The former will not make use of the `...` arguments.

Fix future_map call to use ... arguments to iterate_jitter

---

.github/workflows/call-r-cmd-check.yml
.github/workflows/r4ss-extra-tests.yml
R/SS_output.R
R/SS_read.R
R/download_models.R
R/get_ss3_exe.r
README.md
inst/WORDLIST
man/SS_read.Rd
man/download_models.Rd
man/get_ss3_exe.Rd
tests/testthat/test-readwrite.R
vignettes/r4ss-intro-vignette.Rmd

The nmfs-stock-synthesis organization has been brought into the NMFS GitHub Enterprise and folded into the nmfs-ost organization as discussed in https://github.com/nmfs-ost/ss3-source-code/issues/524.
This PR updates the all links I can find within r4ss to the new locations. There remain comments in the simple_small input files but those files will be updated soon via #893 and it probably makes sense to leave them unchanged until the next SS3 release includes updated comments in the ss_new files.

fix: update nmfs-stock-synthesis links to nmfs-ost

---

R/get_ss3_exe.r

We discussed naming releases ss3_linux, ss3_windows, and ss3_osx. With this change for future releases, I needed to update the get_ss3_exe() function to be able to grab releases that are named either ss_whatever or ss3_whatever.

add if statements for when release exes are names ss3_osname

---

R/file_increment.R
R/jitter.R
inst/WORDLIST
man/file_increment.Rd
man/iterate_jitter.Rd
vignettes/r4ss-intro-vignette.Rmd

Creating a draft PR (for now) so that it's easier to ask for input on, continue development of a fix to this issue (issue #901), and have a place for conversations about development.
@iantaylor-NOAA I altered the `file_increment()` function so that instead of renaming the files, it copies the files under a new name so that the `copy_SS_inputs()` function can find the ss3.par/ss.par file (which is where it seemed to be running into issues before).
@MOshima-PIFSC, if you would like to try grabbing this branch again and testing it out with the ss3diags jitter vignette, that would be great.

Try fixing jitter & file_increment functions

---

R/get_ss3_exe.r

Added the suppressWarnings() to where the function tries ss_win/ss_osx/ss_linux first because when it downloads the exe for the latest release (which is ss3_win/ss3_osx/ss3_linux), there are still some warnings (even though they are expected, they just don't need to be shown to the user). 
The warnings that this should hopefully get rid of are:
Warning messages:
1: In utils::download.file(url, destfile = file.path(dir, "ss3.exe"),  :
downloaded length 0 != reported length 0
2: In utils::download.file(url, destfile = file.path(dir, "ss3.exe"),  :
cannot open URL 'https://github.com/nmfs-ost/ss3-source-code/releases/download/v3.30.22.1/ss_win.exe': HTTP status was '404 Not Found'

add suppressWarnings() to get_ss3_exe()

---

DESCRIPTION
R/SS_output.R

In recent r4ss versions the `SS_output()` function reads the starter file to get the depletion denominator whereas in earlier versions the function could work if only the Report.sso file was available with no additional files.
This change restores the ability to skip the starter file read if the file is not present by relying on a separate output of the depletion denominator (rounded to the nearest percent) in the report file.
Thanks to David Chagaris for report this.

Allow SS_output() to run if only Report.sso is present

---

R/get_SIS_info.R
man/get_SIS_info.Rd
man/r4ss-package.Rd
tests/testthat/test-get_SIS_info.R

This Pull Request includes the following:
* add additional arguments (with default = "XXXX") instead of hard-wiring "XXXX" in output files
* improved rounding in a few places
* `Mgt_Council` input can now be "PFMC" or "GM" (additional councils can be added by anyone with interest) with use of `dplyr::case_when()` to switch among options
* add testthat test #316 
* general code cleanup
@latreesedenson-NOAA, if you have time to take a look at any of these changes and make suggestions or further improvements, please do. In particular, there are a bunch of places where I've filled in the default choice for PFMC assessments, but didn't know how to fill in the GM option, so left it as something like the following. Improvements could be made at any point in the future outside of this pull …

Improve get_SIS_info()

---

R/SSmohnsrho.R

This change fixes the reference year for calculating the Mohn's Rho to compare estimates to the final year with data rather than final year with data + 1 (forecast Mohn's Rho) consistently across parameters.  This should address the error found by @MOshima-PIFSC .

fix: reference year for Mohn's Rho calc #924

---

R/helper_fxns.R
man/add_legend.Rd

I added pt.cex as an argument that can be specified (instead of fixed at 0.7 as was previously) in add_legend(). This gives users more control for changing the size of points in the legend. I set the default to 0.7 so it shouldn't affect any of legends as they currently are. I also updated the documentation for the function by running `devtools::document()`.

Add pt.cex as input argument to add_legend

---

.github/workflows/r4ss-extra-tests.yml
R/get_ss3_exe.r
tests/testthat/test-runs.R

Exe added to v.3.30.21.1 release for mac M2 chips (use aarch64 architecture). Updated get_ss3_exe() function to get that additional exe for macs that have that architecture.
See [successful test of the get_ss3_exe() function on macos-14](https://github.com/nmfs-ost/ss3-test-models/actions/runs/8726931784).

add m2 chip ss3 executable to get_ss3_exe() function

---

DESCRIPTION

There were two lines in the DESCRIPTION file with purrr as an imported package. This PR removes one of them.

fix(DESCRIPTION): Removes duplicated purrr

---

.github/workflows/call-r-cmd-check.yml
R/SS_output.R
R/SSplotRecdist.R
man/SSplotRecdist.Rd

Changes:
- Tables will have separate columns for females and males in the next release of SS3 (see https://github.com/nmfs-ost/ss3-source-code/pull/612). Tables from version 3.30.22 and earlier will automatically relabel "Frac/sex" column to new name "recr_dist_F". 
- If "recr_dist_M" column is present `SSplotRecdist()` will produce separate plots for females and males
- SSplotRecdist() includes new arguments:
- `period` which allows selection of "Initial", "Benchmark", or "End year"
- `sexes` which can be 1, 2, or 1:2
- By default `SS_plots()` will create separate plots to show the the initial year recruitment distribution for females and males in a 2-sex model if the output for males is available

revise read of recruitment distribution table, improve associated plot

---

R/run.R

See issue #853
Create an error if trying to use the wrong executable.

Better error message from `run`

---

R/SSplotComps.R

Simple change resolves 2014 issue #18.
When tail compression is used the tails are compressed to different bins so the aggregated plots can be spiky in confusing ways. Caption will now include the warning "Note: tail compression in use makes aggregated plots more difficult to interpret."

add warning to aggregated plots when tail compression is used #18

---

R/SS_readctl_3.30.R
R/SS_writectl_3.30.R

Thanks to @rosana-ourens for reporting an issue with the r4ss read/write functions when the model setup has different sigma values at different ages. The code also didn't work right when multiple fleets had semiparametric selectivity.
Further changes may be required if there are any user input changes associated with https://github.com/nmfs-ost/ss3-source-code/issues/615 but no reason not to fix things for the existing setup first.

Fix bug in read of semiparametric (2D-AR) selectivity for multiple fleets or multiple sigmas per fleet

---

R/profile.R

The par and admodel files were not being copied and numbered within the dir since this was missing from the file.path for the copy location.

fix: add directory for file copying

---

R/SSplotComparisons.R
R/SSsummarize.R
man/SSsummarize.Rd
tests/testthat/test-basics.R
tests/testthat/test-older_ss3.R

Summary biomass is different from other summarized quantities because it's inclusion in the derived quantities is optional (depends on control files settings under "read specs for more stddev reporting") so the values are either drawn from derived quantities or the time series table, and uncertainty is only available if they're in derived quantities.
Fixes #973
Will merge myself if/when tests pass.

Fix issue with recent incusion of summary biomass in SSsummarize()

---

R/SSsummarize.R

Thanks to Max Cardinale @akatan999 for reporting an issue with the new feature of showing summary biomass when applied to a seasonal model. The code is complex because summary biomass is optionally included in the derived quantities which is an annual value, but also appears in the time series table for each season.
@Rick-Methot-NOAA clarified that summary biomass in derived quantities is for season 1 in a seasonal model so the code in `r4ss::SSsummarize()` now filters for season 1. This facilitates comparisons between models that have summary biomass in derived quantities and those which do not. 
Before this fix, for instance, a model with 37 years and 2 seasons was using the first 37 year/season combinations to fill in the values which was really 18.5 years.
I will merge into main after …

fix bug in SSsummarize for seasonal models

---

R/SS_plots.R
R/SSplotBiology.R
man/SSplotBiology.Rd

Thanks to @akatan999 for finding and reporting yet another bug in r4ss.
The change in headers to be consistent between SS3 and r4ss as discussed in https://github.com/r4ss/r4ss/issues/512 and https://github.com/nmfs-ost/ss3-source-code/pull/608 mostly impacted the r4ss functions related to reading and writing input files, but the biology plots for models that use the empirical weight-at-age depend on reading wtatage.ss_new to get info for the biology plots and I forgot to update the headers used in `SSplotBiology()` to match the new format. This implements that fix.
I also chose to make the plots of the weight-at-age information taller by default. Most png files created by `r4ss::SS_plots()` are `pheight = 6.5` inches wide and `pheight = 4` inches tall which show allow two plots per page …

Fix missing biology plots for empirical weight-at-age models

---

R/get_ss3_exe.r

There are so few mac runners that it causes an error with the api call to GitHub in the `gh()` function when running r_cmd_check on GitHub actions. This fix checks if it's using a GitHub actions runner looking for the `/Users/runner/work/r4ss/r4ss` directory, which is the directory for all github actions run for `r4ss`, OR by looking for the github actions runner temp directory folder text string `/var/folders` which is what is used in the introduction vignette. If it finds either the first directory or the second text string in the directory name, then it does not provide a token parameter to the `gh()` call.

Provide a fix to use tokens for mac github actions runner for get_ss3_exe()

---

R/SS_readctl_3.30.R
R/SS_readpar_3.30.R
R/tune_comps.R

Change variable names to coincide with variable names changes in ss3:
Fleet > fleet
yr > year
Data_type > factor
Value > value
Changes in readctl, readpar, and tunecomps files. 
Partial work towards consistent variable names - issue #141

Small naming changes to coincide with name changes in ss3

---

R/get_ss3_exe.r
tests/testthat/test-get_ss3_exe.R

Testthat was causing an error for the get_ss3_exe() function for the macos-latest runner when run more than once for a particular branch. This PR **should** fix that once and for all after figuring out an additional directory being used later in the test file for that function.
I also updated the test for the function to get rid of a warning that came up.

Solve mac api issue in get_ss3_exe() testthat

---

R/jitter.R
man/jitter.Rd

An [issue from the ss3 repository](https://github.com/nmfs-ost/ss3-source-code/issues/643#issuecomment-2479425005) clarified that the clock SS3 uses to set the jitter seeds is only accurate to the second. The means that, if running jitters in parallel, there is actually a very high likelihood that some seeds get reused, unlike as was originally believed. 
This implements a pause, if jitters are detected to be running in parallel, where the system pauses for `i` seconds for the `i`th jitter.

institute pause for jitter

---

R/SS_readwtatage.R
R/SSplotBiology.R

This code change removes a filter that tested for whether M-at-age was a fixed input or a parameter. It's been in r4ss for at least 10 years and a comment from years ago indicated that I wasn't sure what role it was playing here.
Thanks to @akatan999 for asking why these plots aren't getting created.  
With this Pull Request, if you input a vector of M at age using natural mortality options 3 (age specific) or 4 (age specific with seasonal interpolation), then you will get the same plot you would see with any of the parametric setups of age-dependent M.

Plot fixed M at age

---

R/SSsummarize.R

Fixes issue #996 by combining areas and sexes to get the SmryBio output. This now works and provides the sum(SmryBio) that we expect from the time_series table in the report file, though you might want to test it a bit more than I can right now, so I have included this as a draft PR.

Fix to SSsummarize

---

R/SS_varadjust.R
R/SS_writectl_3.24.R
R/SS_writeforecast.R
R/SS_writestarter.R
R/SS_writewtatage.R
R/SSmakeMmatrix.R

See issue #995 to fix the spacing in the console output of SS_writestarter().

Fix open connection spacing in SS_writestarter

---

R/SS_readctl_3.30.R

I found that the `SS_readctl_3.30()` was not reading the control file correctly for models with age-based discarding and retention.  I have not adding a similar fix to the `SS_readctl_3.24()` function since I don't think that is necessary, plus I don't think age-based retention was correctly implemented in 3.24 models.

fix: add discard parameters for age-based model

---

R/SSplotDiscard.R
R/plotCI.R
man/SSplotDiscard.Rd
man/plotCI.Rd

This PR adds plots of the discard rate or amount with and without model expectation to the set created by `SSplotDiscard()` (called by `SS_plots()`). This helps in cases where discard is in tons with a large range, making small values hard to see. It can also help in cases where discard data is a fraction but some values are small (as in example below from 2017 yellowtail rockfish assessment). In cases where the uncertainty intervals were truncated at 0, I've replaced that with 0.0001 to avoid -Inf in the log-scale plot.

add log-scale plot of discard rates

---

.github/workflows/call-calc-cov-summaries.yml
.github/workflows/call-create-cov-badge.yml
.github/workflows/call-doc-and-style-r.yml
.github/workflows/call-r-cmd-check.yml
.github/workflows/call-spell-check.yml
.github/workflows/call-update-pkgdown.yml

ghactions4r has changed some of their workflows (the calc-cov one), added a workflow to create a badge showing coverage, and will be moving the repo to the nmfs-ost org on May 16 (see discussion [here](https://github.com/nmfs-fish-tools/ghactions4r/issues/159#issuecomment-2840460572))
As Kelli notes below, there is a fork on nmfs-ost already so this can be merged.

ghactions4r updates

---

R/table_exec_summary.R

@e-perl-NOAA noted in https://github.com/pfmc-assessments/Assessment_Class/discussions/77#discussioncomment-13135991 that the `recent_management` table created by `table_exec_summary()` wasn't working right for the yelloweye model which was a result of not aggregating across areas.
@chantelwetzel-noaa, as the primary author of the function, do you want to take a quick look at the change? It's producing the same results as before for yellowtail, and now producing correct results for yelloweye (no extra rows of NA for area 2).

Fix table in table_exec_summary() for multi-area models

---

R/SS_readctl_3.30.R
R/SS_writectl.R
man/SS_writectl.Rd

Adds a section in the SS_readctl_3.30.r file to add a parameter line when there is a link = 5. I also added a section that when the link = 5, it uses the text "Q_base" instead of "LnQ_base" as this is the format that the manual has.
Closes #1020

Fix ss_readctl_3.30 q offset

---

R/SS_changepars.R
man/SS_changepars.Rd

Adjusted `SS_changepars()` function to check whether `strings` input is an exact match to a parameter name in `control.ss_new`. If it is, the matching parameter will be modified by the function. If no exact match is found, the the function will check for parameter names which partially match `strings` and modify these.

"fix SS_changepars() input string matching"

---

.github/workflows/r4ss-extra-tests.yml
tests/testthat/test-test-models.R

This test rewrites the test-test-models.R script called by the r4ss-extra-tests.yml workflow with two goals:
1. speed up the code coverage calculations conducted by codecov. It thus fixed #950. I have no idea why, but running the code on models in sequence instead of parallel (with {furrr}) improved the speed from > 6 hours to about 4.5 hours.
2. provide more informative messages about which model is failing when there's a failure. Because the tests are run in sequence, I could put the call to `test_that()` inside the loop and have the test description include the model name. The resulting message below (copied from https://github.com/r4ss/r4ss/actions/runs/16503548011/job/46668255127#step:12:535) made it easy to diagnose that the problem was caused by running the test-models with the …

Switch to sequential tests for extra testing to calculate code coverage

---

R/comp2long.R

Sorry for taking three pull requests to improve comp2long(), which we're using in a production stock assessment (SW Pacific swordfish) for the first time.
A small but important enhancement of the regular expression, as the first character of bin names had already been shaved off.
Warm wishes from the WCPFC SC meeting in Tonga, where the NOAA Honolulu team is teaching us all the cool r4ss tricks :)

Improve support for two-sex format in comp2long()
